name: Release
on: [push]
#  push:
#    tags:
#      - v*

jobs:
#  release:
#    name: Release
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: actions/setup-node@v1
#        with:
#          node-version: '10.16'
#          scope: '@rtkwlf'
#      - name: Install
#        run: npm install
#      - name: Build
#        run: npm run build
#      - name: Configure .npmrc for publish
#        run: 'echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc'
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
#      - name: Publish to npm
#        run: npm publish --access public
  release-docs:
    name: Release Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'
      - name: Install
        run: npm install
      - name: Build Docs
        run: npm run storybook:docs
      - name: Commit Documentation Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Releasing new documentation"
      - name: Push Documentation
        env:
          SOURCE_BRANCH: master
          TARGET_BRANCH: aaho-doc-test
        run: echo ${SOURCE_BRANCH} and ${TARGET_BRANCH}
#        run: git push --force --quiet https://${{secrets.GITHUB_TOKEN}}@github.com/rtkwlf/ui ${SOURCE_BRANCH}:${TARGET_BRANCH}
