name: Deploy
on: [push]
#   push:
#     branches:
#       - '!master'
#     tags:
#       - v*

jobs:
  main-tests:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'
      - run: npm install
      - run: npm run build
      - run: echo 'npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}' > .npmrc
      - run: npm publish
